# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: false  # We'll do it manually

    - name: Confirm submodule directories before manual clone
      run: |
        echo "🔍 Checking submodule directories before sparse clone:"
        ls -la
        ls -la bwv1006 || echo "bwv1006 not yet populated"
        ls -la bwv543 || echo "bwv543 not yet populated"

    - name: Sparse clone submodules manually
      run: |
        for sub in bwv1006 bwv543; do
          echo "⬇️ Cloning $sub with sparse checkout"
          git clone --filter=blob:none --sparse --no-checkout https://github.com/musicollator/$sub.git $sub
          cd $sub
          git sparse-checkout init --cone
          git sparse-checkout set exports/
          git read-tree -mu HEAD
          cd ..
        done

    - name: List contents of submodules
      run: |
        for sub in bwv1006 bwv543; do
          echo "🧾 Files in $sub after sparse checkout:"
          ls -la $sub
          echo ""
          echo "📂 Contents of $sub exports directory:"
          ls -la $sub/exports || echo "No exports directory found"
          echo ""
        done

    - name: Create deployment directory
      run: |
        mkdir deploy
        cp index.html deploy/
        cp *.js deploy/
        cp manifest.json deploy/
        cp sw.js deploy/
        cp -r media deploy/
        for sub in bwv1006 bwv543; do
          cp -r $sub deploy/
        done

    - name: Verify PWA files in deployment
      run: |
        echo "🔍 Verifying PWA files in deployment directory:"
        ls -la deploy/
        echo ""
        echo "📱 PWA manifest file:"
        ls -la deploy/manifest.json || echo "❌ manifest.json missing"
        echo ""
        echo "⚙️ Service worker file:"
        ls -la deploy/sw.js || echo "❌ sw.js missing"
        echo ""
        echo "🎨 PWA icons directory:"
        ls -la deploy/media/icons/ || echo "❌ icons directory missing"
        echo ""
        echo "📊 Total deployment size:"
        du -sh deploy/

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './deploy'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4